import { Loan, EMI, LoanSummary } from '@/types/loan.types';
import { MonthlyData, LoanDistribution, AIInsight, Reminder, FinancialHealthMetric } from '@/types/analytics.types';
import { User } from '@/types/user.types';
import { PaymentHistory } from '@/types/payment.types';
import { FinancialHealthScore, Recommendation } from '@/types/health.types';
import { Notification } from '@/types/notification.types';

// ─── USER ────────────────────────────────────────────────────────────────────
export const DUMMY_USER: User = {
  id: 'usr_001',
  name: 'Ranjith Kumar',
  email: 's.ranjithkumaroffl@gmail.com',
  phone: '+919876543210',
  avatar: undefined,
  creditScore: 742,
  financialHealthScore: 74,
  monthlyIncome: 85000,
  joinedAt: '2023-06-15T00:00:00.000Z',
  kycVerified: true,
  biometricEnabled: false,
  notificationsEnabled: true,
  preferredLanguage: 'en',
  preferredCurrency: 'INR',
};

// ─── LOANS ───────────────────────────────────────────────────────────────────
export const DUMMY_LOANS: Loan[] = [
  {
    id: 'loan_001',
    userId: 'usr_001',
    lenderName: 'HDFC Bank',
    lenderLogo: undefined,
    type: 'home',
    status: 'active',
    principalAmount: 4500000,
    outstandingAmount: 3820000,
    interestRate: 8.5,
    tenureMonths: 240,
    startDate: '2021-03-01',
    endDate: '2041-03-01',
    emiAmount: 39090,
    emiDueDate: 5,
    totalPaid: 680000,
    totalInterestPaid: 290000,
    nextEMIDate: '2026-06-05',
    accountNumber: 'HDFC****4521',
    prepaymentAllowed: true,
    forecloseCharges: 2,
    lastPaymentDate: '2026-05-05',
    lastPaymentAmount: 39090,
  },
  {
    id: 'loan_002',
    userId: 'usr_001',
    lenderName: 'ICICI Bank',
    lenderLogo: undefined,
    type: 'car',
    status: 'active',
    principalAmount: 800000,
    outstandingAmount: 520000,
    interestRate: 9.2,
    tenureMonths: 60,
    startDate: '2022-08-01',
    endDate: '2027-08-01',
    emiAmount: 16650,
    emiDueDate: 10,
    totalPaid: 280000,
    totalInterestPaid: 98000,
    nextEMIDate: '2026-06-10',
    accountNumber: 'ICICI****7823',
    prepaymentAllowed: true,
    forecloseCharges: 0,
    lastPaymentDate: '2026-05-10',
    lastPaymentAmount: 16650,
  },
  {
    id: 'loan_003',
    userId: 'usr_001',
    lenderName: 'Bajaj Finserv',
    lenderLogo: undefined,
    type: 'personal',
    status: 'active',
    principalAmount: 300000,
    outstandingAmount: 180000,
    interestRate: 14.5,
    tenureMonths: 36,
    startDate: '2024-01-01',
    endDate: '2027-01-01',
    emiAmount: 10290,
    emiDueDate: 1,
    totalPaid: 120000,
    totalInterestPaid: 42000,
    nextEMIDate: '2026-07-01',
    accountNumber: 'BAJAJ****2341',
    prepaymentAllowed: true,
    forecloseCharges: 4,
    lastPaymentDate: '2026-06-01',
    lastPaymentAmount: 10290,
  },
  {
    id: 'loan_004',
    userId: 'usr_001',
    lenderName: 'SBI',
    lenderLogo: undefined,
    type: 'education',
    status: 'active',
    principalAmount: 1200000,
    outstandingAmount: 950000,
    interestRate: 7.8,
    tenureMonths: 120,
    startDate: '2020-07-01',
    endDate: '2030-07-01',
    emiAmount: 14350,
    emiDueDate: 15,
    totalPaid: 250000,
    totalInterestPaid: 95000,
    nextEMIDate: '2026-06-15',
    accountNumber: 'SBI****9912',
    prepaymentAllowed: true,
    forecloseCharges: 0,
    lastPaymentDate: '2026-05-15',
    lastPaymentAmount: 14350,
  },
];

// ─── EMIS ─────────────────────────────────────────────────────────────────────
export const DUMMY_UPCOMING_EMIS: EMI[] = [
  {
    id: 'emi_001',
    loanId: 'loan_001',
    loanName: 'HDFC Home Loan',
    lenderName: 'HDFC Bank',
    loanType: 'home',
    amount: 39090,
    dueDate: '2026-06-05',
    status: 'upcoming',
    penaltyAmount: 0,
    month: 6,
    year: 2026,
    installmentNumber: 64,
    totalInstallments: 240,
  },
  {
    id: 'emi_002',
    loanId: 'loan_002',
    loanName: 'ICICI Car Loan',
    lenderName: 'ICICI Bank',
    loanType: 'car',
    amount: 16650,
    dueDate: '2026-06-10',
    status: 'upcoming',
    penaltyAmount: 0,
    month: 6,
    year: 2026,
    installmentNumber: 46,
    totalInstallments: 60,
  },
  {
    id: 'emi_003',
    loanId: 'loan_004',
    loanName: 'SBI Education Loan',
    lenderName: 'SBI',
    loanType: 'education',
    amount: 14350,
    dueDate: '2026-06-15',
    status: 'upcoming',
    penaltyAmount: 0,
    month: 6,
    year: 2026,
    installmentNumber: 72,
    totalInstallments: 120,
  },
  {
    id: 'emi_004',
    loanId: 'loan_003',
    loanName: 'Bajaj Personal Loan',
    lenderName: 'Bajaj Finserv',
    loanType: 'personal',
    amount: 10290,
    dueDate: '2026-07-01',
    status: 'pending',
    penaltyAmount: 0,
    month: 7,
    year: 2026,
    installmentNumber: 19,
    totalInstallments: 36,
  },
];

export const DUMMY_EMI_HISTORY: EMI[] = [
  {
    id: 'emi_h001',
    loanId: 'loan_001',
    loanName: 'HDFC Home Loan',
    lenderName: 'HDFC Bank',
    loanType: 'home',
    amount: 39090,
    dueDate: '2026-05-05',
    status: 'paid',
    paidDate: '2026-05-05',
    paidAmount: 39090,
    penaltyAmount: 0,
    paymentMethod: 'auto_debit',
    receiptNumber: 'RCP20260505001',
    month: 5,
    year: 2026,
    installmentNumber: 63,
    totalInstallments: 240,
  },
  {
    id: 'emi_h002',
    loanId: 'loan_002',
    loanName: 'ICICI Car Loan',
    lenderName: 'ICICI Bank',
    loanType: 'car',
    amount: 16650,
    dueDate: '2026-05-10',
    status: 'paid',
    paidDate: '2026-05-10',
    paidAmount: 16650,
    penaltyAmount: 0,
    paymentMethod: 'upi',
    receiptNumber: 'RCP20260510002',
    month: 5,
    year: 2026,
    installmentNumber: 45,
    totalInstallments: 60,
  },
  {
    id: 'emi_h003',
    loanId: 'loan_004',
    loanName: 'SBI Education Loan',
    lenderName: 'SBI',
    loanType: 'education',
    amount: 14350,
    dueDate: '2026-05-15',
    status: 'paid',
    paidDate: '2026-05-15',
    paidAmount: 14350,
    penaltyAmount: 0,
    paymentMethod: 'netbanking',
    receiptNumber: 'RCP20260515003',
    month: 5,
    year: 2026,
    installmentNumber: 71,
    totalInstallments: 120,
  },
  {
    id: 'emi_h004',
    loanId: 'loan_003',
    loanName: 'Bajaj Personal Loan',
    lenderName: 'Bajaj Finserv',
    loanType: 'personal',
    amount: 10290,
    dueDate: '2026-04-05',
    status: 'overdue',
    penaltyAmount: 500,
    month: 4,
    year: 2026,
    installmentNumber: 16,
    totalInstallments: 36,
  },
  {
    id: 'emi_h005',
    loanId: 'loan_001',
    loanName: 'HDFC Home Loan',
    lenderName: 'HDFC Bank',
    loanType: 'home',
    amount: 39090,
    dueDate: '2026-04-05',
    status: 'paid',
    paidDate: '2026-04-05',
    paidAmount: 39090,
    penaltyAmount: 0,
    paymentMethod: 'auto_debit',
    receiptNumber: 'RCP20260405001',
    month: 4,
    year: 2026,
    installmentNumber: 62,
    totalInstallments: 240,
  },
  {
    id: 'emi_h006',
    loanId: 'loan_002',
    loanName: 'ICICI Car Loan',
    lenderName: 'ICICI Bank',
    loanType: 'car',
    amount: 16650,
    dueDate: '2026-04-10',
    status: 'paid',
    paidDate: '2026-04-10',
    paidAmount: 16650,
    penaltyAmount: 0,
    paymentMethod: 'upi',
    receiptNumber: 'RCP20260410002',
    month: 4,
    year: 2026,
    installmentNumber: 44,
    totalInstallments: 60,
  },
];

// ─── LOAN SUMMARY ─────────────────────────────────────────────────────────────
export const DUMMY_LOAN_SUMMARY: LoanSummary = {
  totalLoans: 4,
  activeLoans: 4,
  totalOutstanding: 5470000,
  totalEMIPerMonth: 80380,
  nextEMIDue: '2026-06-05',
  nextEMIAmount: 39090,
  overdueAmount: 500,
  overdueCount: 1,
  totalPaidThisYear: 963720,
  debtToIncomeRatio: 94.6,
};

// ─── PAYMENTS ─────────────────────────────────────────────────────────────────
export const DUMMY_PAYMENT_HISTORY: PaymentHistory[] = [
  { id: 'pmt_001', loanId: 'loan_001', emiId: 'emi_h001', amount: 39090, date: '2026-05-05', method: 'auto_debit', status: 'success', receiptNumber: 'RCP20260505001' },
  { id: 'pmt_002', loanId: 'loan_002', emiId: 'emi_h002', amount: 16650, date: '2026-05-10', method: 'upi', status: 'success', receiptNumber: 'RCP20260510002' },
  { id: 'pmt_003', loanId: 'loan_004', emiId: 'emi_h003', amount: 14350, date: '2026-05-15', method: 'netbanking', status: 'success', receiptNumber: 'RCP20260515003' },
  { id: 'pmt_004', loanId: 'loan_001', emiId: 'emi_h005', amount: 39090, date: '2026-04-05', method: 'auto_debit', status: 'success', receiptNumber: 'RCP20260405001' },
  { id: 'pmt_005', loanId: 'loan_002', emiId: 'emi_h006', amount: 16650, date: '2026-04-10', method: 'upi', status: 'success', receiptNumber: 'RCP20260410002' },
  { id: 'pmt_006', loanId: 'loan_003', emiId: 'emi_h004', amount: 10290, date: '2026-04-05', method: 'upi', status: 'failed', receiptNumber: undefined },
];

// ─── ANALYTICS ───────────────────────────────────────────────────────────────
export const DUMMY_MONTHLY_DATA: MonthlyData[] = [
  { month: 'Jan', year: 2026, totalPaid: 80380, principalPaid: 32150, interestPaid: 48230, savingsAmount: 5000 },
  { month: 'Feb', year: 2026, totalPaid: 80380, principalPaid: 32800, interestPaid: 47580, savingsAmount: 5000 },
  { month: 'Mar', year: 2026, totalPaid: 80380, principalPaid: 33500, interestPaid: 46880, savingsAmount: 8000 },
  { month: 'Apr', year: 2026, totalPaid: 80380, principalPaid: 34200, interestPaid: 46180, savingsAmount: 5000 },
  { month: 'May', year: 2026, totalPaid: 80380, principalPaid: 34900, interestPaid: 45480, savingsAmount: 12000 },
  { month: 'Jun', year: 2026, totalPaid: 80380, principalPaid: 35600, interestPaid: 44780, savingsAmount: 5000 },
];

export const DUMMY_LOAN_DISTRIBUTION: LoanDistribution[] = [
  { type: 'Home Loan', amount: 3820000, percentage: 69.8, color: '#7C3AED' },
  { type: 'Education Loan', amount: 950000, percentage: 17.4, color: '#06B6D4' },
  { type: 'Car Loan', amount: 520000, percentage: 9.5, color: '#10B981' },
  { type: 'Personal Loan', amount: 180000, percentage: 3.3, color: '#F59E0B' },
];

// ─── FINANCIAL HEALTH ─────────────────────────────────────────────────────────
export const DUMMY_HEALTH_METRICS: FinancialHealthMetric[] = [
  { label: 'EMI to Income', score: 30, maxScore: 100, status: 'poor', description: 'Your EMIs consume 94.6% of income. Aim below 40%.' },
  { label: 'Payment History', score: 85, maxScore: 100, status: 'excellent', description: '5 of 6 recent EMIs paid on time.' },
  { label: 'Credit Utilization', score: 72, maxScore: 100, status: 'good', description: 'Credit card utilization below 30% threshold.' },
  { label: 'Debt Consistency', score: 80, maxScore: 100, status: 'good', description: 'Regular, consistent repayments observed.' },
  { label: 'Savings Ratio', score: 40, maxScore: 100, status: 'average', description: 'Savings are 5.9% of income. Target 20%.' },
];

export const DUMMY_FINANCIAL_HEALTH: FinancialHealthScore = {
  overallScore: 74,
  creditScore: 742,
  emiToIncomeRatio: 94.6,
  creditUtilization: 28,
  paymentHistoryScore: 85,
  debtConsistencyScore: 80,
  savingsRatio: 5.9,
  metrics: DUMMY_HEALTH_METRICS,
  lastUpdated: '2026-06-01T00:00:00.000Z',
  trend: 'up',
  trendValue: 3,
};

// ─── AI INSIGHTS ─────────────────────────────────────────────────────────────
export const DUMMY_AI_INSIGHTS: AIInsight[] = [
  {
    id: 'ins_001',
    type: 'opportunity',
    title: 'Pre-close Personal Loan & Save ₹18,420',
    description: 'Your Bajaj Personal Loan has only 17 EMIs left. Pre-closing now saves ₹18,420 in interest. Use your emergency fund top-up next month to clear this.',
    actionLabel: 'View Pre-closure Plan',
    actionRoute: '/loan/loan_003',
    savingsEstimate: 18420,
    priority: 'high',
    createdAt: '2026-06-01T08:00:00.000Z',
    isRead: false,
  },
  {
    id: 'ins_002',
    type: 'tip',
    title: 'Avalanche Strategy Could Save ₹2.1L',
    description: 'Paying an extra ₹5,000/month on your Bajaj Personal Loan (14.5% rate) while maintaining minimums on others will save ₹2.1L in total interest.',
    actionLabel: 'Start Avalanche Plan',
    actionRoute: '/ai-insights',
    savingsEstimate: 210000,
    priority: 'high',
    createdAt: '2026-06-01T07:00:00.000Z',
    isRead: false,
  },
  {
    id: 'ins_003',
    type: 'warning',
    title: 'Debt-to-Income Ratio is High',
    description: 'Your EMI burden is 94.6% of income. Financial advisors recommend keeping it below 40%. Consider part-prepayment or income enhancement.',
    priority: 'high',
    createdAt: '2026-05-30T10:00:00.000Z',
    isRead: true,
  },
  {
    id: 'ins_004',
    type: 'achievement',
    title: 'Paid ₹9.6L This Year!',
    description: "You've been consistent — ₹9.6 Lakhs paid across all loans in 2026. Your outstanding has reduced by ₹2.1L this year alone. Keep it up!",
    priority: 'low',
    createdAt: '2026-05-28T09:00:00.000Z',
    isRead: true,
  },
  {
    id: 'ins_005',
    type: 'opportunity',
    title: 'Home Loan Balance Transfer Saves ₹86K/yr',
    description: 'Current rate: 8.5%. Balance transfer rate: 7.9%. Saving potential: ₹86,400/year. Refinancing can drastically cut interest.',
    actionLabel: 'Compare Rates',
    savingsEstimate: 86400,
    priority: 'medium',
    createdAt: '2026-05-25T08:00:00.000Z',
    isRead: false,
  },
  {
    id: 'ins_006',
    type: 'tip',
    title: 'Auto-Debit Improves Credit Score',
    description: 'Set up auto-debit for Car and Personal loans (currently manual). On-time payments via auto-debit can improve your credit score by 15–30 points.',
    actionLabel: 'Set Up Auto-Debit',
    priority: 'medium',
    createdAt: '2026-05-22T11:00:00.000Z',
    isRead: true,
  },
];

// ─── RECOMMENDATIONS ──────────────────────────────────────────────────────────
export const DUMMY_RECOMMENDATIONS: Recommendation[] = [
  {
    id: 'rec_001',
    type: 'preclosure',
    loanId: 'loan_003',
    loanName: 'Bajaj Personal Loan',
    title: 'Pre-close Personal Loan',
    description: 'Pay off ₹1,80,000 outstanding to save ₹18,420 in future interest.',
    savingsAmount: 18420,
    requiredAmount: 180000,
    timeToImplement: 'Immediate',
    difficulty: 'medium',
    priority: 'high',
    steps: [
      'Contact Bajaj Finserv for pre-closure statement',
      'Check for foreclosure charges (4% = ₹7,200)',
      'Net savings after charges: ₹11,220',
      'Use emergency fund or bonus to pre-close',
    ],
  },
  {
    id: 'rec_002',
    type: 'avalanche',
    title: 'Debt Avalanche Strategy',
    description: 'Pay highest-rate loan first. Extra ₹5K/month on Personal Loan saves ₹2.1L.',
    savingsAmount: 210000,
    monthlyExtraPayment: 5000,
    timeToImplement: '17 months',
    difficulty: 'easy',
    priority: 'high',
    payoffOrder: ['loan_003', 'loan_002', 'loan_004', 'loan_001'],
    steps: [
      'Pay minimum on all loans',
      'Allocate extra ₹5,000 to Bajaj Personal Loan (14.5% rate)',
      'Once closed, redirect ₹15,290 to ICICI Car Loan (9.2%)',
      'Continue cascade until all loans cleared',
    ],
  },
  {
    id: 'rec_003',
    type: 'snowball',
    title: 'Debt Snowball Strategy',
    description: 'Pay smallest balance first for psychological wins. Closes Personal Loan in 17 months.',
    savingsAmount: 145000,
    monthlyExtraPayment: 5000,
    timeToImplement: '17 months',
    difficulty: 'easy',
    priority: 'medium',
    payoffOrder: ['loan_003', 'loan_002', 'loan_004', 'loan_001'],
    steps: [
      'Pay minimum on all loans',
      'Allocate extra ₹5,000 to Bajaj Personal Loan (smallest balance)',
      'After closure, redirect all freed EMI to Car Loan',
      'Build momentum with each payoff',
    ],
  },
  {
    id: 'rec_004',
    type: 'refinance',
    loanId: 'loan_001',
    loanName: 'HDFC Home Loan',
    title: 'Refinance Home Loan at 7.9%',
    description: 'Balance transfer from 8.5% to 7.9% saves ₹86,400/year on your home loan.',
    savingsAmount: 86400,
    newInterestRate: 7.9,
    timeToImplement: '4-6 weeks',
    difficulty: 'hard',
    priority: 'medium',
    steps: [
      'Get balance transfer quote from SBI/Kotak',
      'Compare processing fees vs 10-year savings',
      'Apply with updated income proof and property docs',
      'Approval typically in 3–4 weeks',
    ],
  },
  {
    id: 'rec_005',
    type: 'credit_improvement',
    title: 'Improve Credit Score by 40+ Points',
    description: 'Set up auto-debit for all loans, reduce credit card utilization, and dispute errors in your report.',
    priority: 'medium',
    difficulty: 'easy',
    timeToImplement: '3-6 months',
    steps: [
      'Enable auto-debit for ICICI Car Loan and Bajaj Personal Loan',
      'Keep credit card balance below 20% of limit',
      'Check CIBIL report for errors and dispute if any',
      'Avoid new credit applications for 6 months',
    ],
  },
];

// ─── REMINDERS ────────────────────────────────────────────────────────────────
export const DUMMY_REMINDERS: Reminder[] = [
  { id: 'rem_001', loanId: 'loan_001', loanName: 'HDFC Home Loan', lenderName: 'HDFC Bank', emiAmount: 39090, dueDate: '2026-06-05', reminderDays: [3, 1], isActive: true, notifyVia: ['push', 'sms'] },
  { id: 'rem_002', loanId: 'loan_002', loanName: 'ICICI Car Loan', lenderName: 'ICICI Bank', emiAmount: 16650, dueDate: '2026-06-10', reminderDays: [2], isActive: true, notifyVia: ['push'] },
  { id: 'rem_003', loanId: 'loan_004', loanName: 'SBI Education Loan', lenderName: 'SBI', emiAmount: 14350, dueDate: '2026-06-15', reminderDays: [5, 2, 1], isActive: true, notifyVia: ['push', 'email'] },
  { id: 'rem_004', loanId: 'loan_003', loanName: 'Bajaj Personal Loan', lenderName: 'Bajaj Finserv', emiAmount: 10290, dueDate: '2026-07-01', reminderDays: [7, 3, 1], isActive: false, notifyVia: ['push'] },
];

// ─── NOTIFICATIONS ────────────────────────────────────────────────────────────
export const DUMMY_NOTIFICATIONS: Notification[] = [
  {
    id: 'notif_001',
    type: 'due_soon',
    title: 'EMI Due in 4 Days',
    body: 'HDFC Home Loan EMI of ₹39,090 is due on June 5, 2026.',
    loanId: 'loan_001',
    amount: 39090,
    dueDate: '2026-06-05',
    isRead: false,
    createdAt: '2026-06-01T09:00:00.000Z',
  },
  {
    id: 'notif_002',
    type: 'payment_success',
    title: 'Payment Successful',
    body: 'SBI Education Loan EMI of ₹14,350 paid successfully on May 15.',
    loanId: 'loan_004',
    amount: 14350,
    isRead: true,
    createdAt: '2026-05-15T10:30:00.000Z',
  },
  {
    id: 'notif_003',
    type: 'overdue',
    title: 'EMI Overdue',
    body: 'Bajaj Personal Loan EMI is overdue. Penalty: ₹500 applied.',
    loanId: 'loan_003',
    amount: 10290,
    dueDate: '2026-04-05',
    isRead: false,
    createdAt: '2026-04-06T08:00:00.000Z',
  },
  {
    id: 'notif_004',
    type: 'insight',
    title: 'New AI Insight Available',
    body: 'Pre-closing your Personal Loan could save ₹18,420 in interest.',
    isRead: false,
    createdAt: '2026-06-01T08:00:00.000Z',
  },
  {
    id: 'notif_005',
    type: 'payment_success',
    title: 'Payment Successful',
    body: 'HDFC Home Loan EMI of ₹39,090 paid via Auto-Debit on May 5.',
    loanId: 'loan_001',
    amount: 39090,
    isRead: true,
    createdAt: '2026-05-05T06:15:00.000Z',
  },
];

// ─── AMORTIZATION HELPER ──────────────────────────────────────────────────────
export function generateAmortization(loan: Loan) {
  const entries = [];
  const monthlyRate = loan.interestRate / 100 / 12;
  let outstanding = loan.principalAmount;

  for (let i = 1; i <= loan.tenureMonths; i++) {
    const interest = outstanding * monthlyRate;
    const principal = loan.emiAmount - interest;
    outstanding = Math.max(0, outstanding - principal);

    const date = new Date(loan.startDate);
    date.setMonth(date.getMonth() + i - 1);

    const now = new Date();
    const entryDate = new Date(date);
    const isPast = entryDate < now;
    const isCurrent = entryDate.getMonth() === now.getMonth() && entryDate.getFullYear() === now.getFullYear();
    const status = isPast ? 'paid' : isCurrent ? 'upcoming' : 'pending';

    entries.push({
      installmentNumber: i,
      date: date.toISOString().split('T')[0],
      emiAmount: loan.emiAmount,
      principalComponent: Math.max(0, principal),
      interestComponent: Math.max(0, interest),
      outstandingPrincipal: outstanding,
      status,
    });
  }
  return entries;
}
